services:
  app:
    platform: linux/x86_64
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "7780:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"