"use client"

export const ID_KELOMPOK_AKUN_PENDAPATAN = 6
export const ID_KELOMPOK_AKUN_BEBAN_POKOK_PENJUALAN = 7
export const ID_KELOMPOK_AKUN_BEBAN_OPERASIONAL = 8
export const ID_KELOMPOK_AKUN_BEBAN_LAIN_LAIN = 9
export const ID_KELOMPOK_AKUN_LABA_RUGI = 10

export const POSISI_NERACA_ASET = "ASET"
export const POSISI_NERACA_UTANG = "UTANG"
export const POSISI_NERACA_MODAL = "MODAL"

export const ID_AKUN_LABA_KOTOR = 47
export const ID_AKUN_LABA_OPERASIONAL = 48
export const ID_AKUN_LABA_BERSIH = 50
export const ID_AKUN_LABA_DITAHAN = 26
export const ID_AKUN_IKHTISAR_LABA_RUGI = 56
export const ID_AKUN_LABA_TAHUN_BERJALAN = 27
export const ID_AKUN_DISKON_PENJUALAN = 29